product = input()
price = input()
weight = input()
money = int(input())
print('Чек')
print(product, ' - ', weight, 'кг', ' - ', price, 'руб/кг', sep='')
print('Итого: ', int(price) * int(weight), 'руб', sep='')
print('Внесено: ', money, 'руб', sep='')
print('Сдача: ', money - int(price) * int(weight), 'руб', sep='')
